version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'database'
      MYSQL_PASSWORD: 'database'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql